theme: jekyll-theme-architect
title: AIOnline
subtitle: Leon's Secret Garden
description: A Tech-blog in Artificial Intelligence, especially in Natural Language Processing at present. Cognitive Science, Psychology & Philosophy are also preferred.
show_downloads: false
