theme: jekyll-theme-architect
title: AIOnline
description: Leon's Secret Garden
# Welcome to Leon's Tech-blog in Artificial Intelligence, especially in Natural Language Processing at present. Cognitive Science, Psychology & Philosophy are also preferred.
show_downloads: false
